Naming/AccessorMethodName:
  Enabled: false
Naming/BinaryOperatorParameterName:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
Style/MixinUsage:
  Enabled: false
Style/PreferredHashMethods:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Style/SymbolArray:
  Enabled: true
